name: angular_architecture
description: Developer Guide Intro
version: 0.0.1

environment:
  sdk: '>=2.0.0-dev.51.0 <2.0.0'

dependencies:
  angular: ^5.0.0-alpha
  angular_forms: ^2.0.0-alpha

dev_dependencies:
  build_runner: ^0.8.6
  build_test: ^0.10.2
  build_web_compilers: ^0.3.7
