name: angular_architecture
description: Developer Guide Intro
version: 0.0.1

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.0.0
  angular_forms: ^2.0.0

dev_dependencies:
  build_runner: ^1.0.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
