name: developer_guide_intro
description: Developer Guide Intro
version: 0.0.1

environment:
  sdk: '>=2.0.0-dev.32.0 <2.0.0'

dependencies:
  angular: ^5.0.0-alpha
  angular_forms: ^2.0.0-alpha

dev_dependencies:
  build_runner: ^0.8.2
  build_test: ^0.10.0
  build_web_compilers: ^0.3.6
