name: template_syntax
description: Template Syntax
version: 0.0.1

environment:
  sdk: '>=2.0.0-dev.32.0 <2.0.0'

dependencies:
  angular: ^5.0.0-alpha
  angular_components: ^0.9.0-alpha
  angular_forms: ^2.0.0-alpha

dev_dependencies:
  angular_test: ^2.0.0-alpha
  build_runner: ^0.8.2
  build_test: ^0.10.0
  build_web_compilers: ^0.3.6
  test: ^0.12.30

dependency_overrides:
  angular: ^5.0.0-alpha+9
  angular_forms: ^2.0.0-alpha+1
  # Temporarily use mock pageloader (https://github.com/dart-lang/site-webdev/issues/1351):
  pageloader:
     git:
       url: https://github.com/dart-lang/site-webdev.git
       ref: 5-dev
       path: examples/util/pageloader
#    path: ../../../util/pageloader
