name: template_syntax
description: Template Syntax
version: 0.0.1

environment:
  sdk: '>=2.0.0-dev.56.0 <2.0.0'

dependencies:
  angular: ^5.0.0-alpha+13
  angular_components: ^0.9.0-alpha+14
  angular_forms: ^2.0.0-alpha

dev_dependencies:
  angular_test: ^2.0.0-alpha
  build_runner: ^0.8.9
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  pageloader: ^3.0.0-alpha
  test: ^0.12.35
