name: template_syntax
description: Template Syntax
version: 0.0.1

environment:
  sdk: '>=2.0.0-dev.60.0 <2.0.0'

dependencies:
  angular: ^5.0.0-alpha+15
  angular_components: ^0.9.0-alpha+15
  angular_forms: ^2.0.0-alpha

dev_dependencies:
  angular_test: ^2.0.0-alpha
  build_runner: ^0.8.10
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  pageloader: ^3.0.0-alpha
  test: ^0.12.42

dependency_overrides:
  build_config: ^0.3.0
