# #docregion
name: server_communication
description: Server Communication
version: 0.0.1

environment:
  sdk: '>=2.0.0-dev.46.0 <2.0.0'

dependencies:
  angular: ^5.0.0-alpha
  http: ^0.11.0
  jsonpadding: ^0.1.0
  stream_transform: ^0.0.5

dev_dependencies:
  build_runner: ^0.8.2
  build_test: ^0.10.0
  build_web_compilers: ^0.3.6
