dist: trusty
sudo: required
language: dart
dart: 2.0.0-dev.61.0

cache:
  timeout: 300
  bundler: true
  directories:
  - $HOME/.pub-cache
  - $HOME/.nvm
  - $HOME/.rvm
  - .dart_tool
  - node_modules
  # - publish # takes too long to cache and check for freshness
  - tmp # TODO: rename to cache or .cache
  # Examples:
  - examples/ng/doc/node_modules
  # examples/**/.dart_tool
  - examples/acx/lottery/1-base/.dart_tool
  - examples/acx/lottery/2-starteasy/.dart_tool
  - examples/acx/lottery/3-usebuttons/.dart_tool
  - examples/acx/lottery/4-final/.dart_tool
  - examples/ng/api/common/pipes/.dart_tool
  - examples/ng/api/core/ngzone/.dart_tool
  - examples/ng/doc/architecture/.dart_tool
  - examples/ng/doc/attribute-directives/.dart_tool
  - examples/ng/doc/component-styles/.dart_tool
  - examples/ng/doc/dependency-injection/.dart_tool
  - examples/ng/doc/displaying-data/.dart_tool
  - examples/ng/doc/forms/.dart_tool
  - examples/ng/doc/hierarchical-dependency-injection/.dart_tool
  - examples/ng/doc/lifecycle-hooks/.dart_tool
  - examples/ng/doc/pipes/.dart_tool
  - examples/ng/doc/quickstart/.dart_tool
  - examples/ng/doc/router/.dart_tool
  - examples/ng/doc/security/.dart_tool
  - examples/ng/doc/server-communication/.dart_tool
  - examples/ng/doc/structural-directives/.dart_tool
  - examples/ng/doc/template-syntax/.dart_tool
  - examples/ng/doc/toh-0/.dart_tool
  - examples/ng/doc/toh-1/.dart_tool
  - examples/ng/doc/toh-2/.dart_tool
  - examples/ng/doc/toh-3/.dart_tool
  - examples/ng/doc/toh-4/.dart_tool
  - examples/ng/doc/toh-5/.dart_tool
  - examples/ng/doc/toh-6/.dart_tool
  - examples/ng/doc/user-input/.dart_tool

addons:
  chrome: stable

env:
  global:
    # https://github.com/dart-lang/site-webdev/issues/1638
    # - DART_VM_OPTIONS=--preview-dart-2
    - DISPLAY=:99.0
    - JEKYLL_ENV=production
    # E2E and TEST: use --skip=t1|t2|...|tx to skip tests
    - E2E_OPT1="--fast --filter=examples/ng/doc/[a-l]"
    - E2E_OPT2="--fast --filter=examples/ng/doc/[m-z] --skip=toh"
    - E2E_OPT3="--fast --filter=examples/ng/doc/toh"
    - TEST_OPT=""
    - TZ=US/Pacific # normalize build timestamp

matrix:
  fast_finish: true
  allow_failures:
    - env: CI_TASK="test $TEST_OPT"
    - env: CI_TASK="e2e $E2E_OPT1"
    - env: CI_TASK="e2e $E2E_OPT2"
    - env: CI_TASK="e2e $E2E_OPT3"
    - env: CI_TASK="e2e $E2E_OPT1 --web-compiler=dart2js"
    - env: CI_TASK="e2e $E2E_OPT2 --web-compiler=dart2js"
    - env: CI_TASK="e2e $E2E_OPT3 --web-compiler=dart2js"

before_install:
  - source ./scripts/env-set.sh
  - ./scripts/before-install.sh

install:
  - ./scripts/install.sh

before_script:
  - ./scripts/browser.sh

jobs:
  include:
    ## STAGE ----------------------------------------------
    - stage: cache warmup and basic checks
      env: CI_TASK="build"
      script:
      - pub get
      - bundle install
      - gulp ng-pkg-pub-get # --skip=package_name|...
      - gulp _build-prep --clean
    # TODO: run analyzer (and dartfmt?) over examples
    # Until we run the analyzer, we aren't gaining much by warming up the test and e2e caches.
    # - env: CI_TASK="test $TEST_OPT"
    # - env: CI_TASK="e2e $E2E_OPT1"
    # - env: CI_TASK="e2e $E2E_OPT2"
    # - env: CI_TASK="e2e $E2E_OPT3"
    # - env: CI_TASK="e2e $E2E_OPT1 --web-compiler=dart2js"
    # - env: CI_TASK="e2e $E2E_OPT2 --web-compiler=dart2js"
    # - env: CI_TASK="e2e $E2E_OPT3 --web-compiler=dart2js"

    ## STAGE ----------------------------------------------
    - stage: build site and test examples
      env: CI_TASK="build"
      script:
        - pub get
        - ./scripts/write-ci-info.sh -v
        - gulp _api-doc-prep --use-cached-api-doc --dartdoc=all
        - gulp _jekyll-build _examples-cp-to-site-folder
        - ls -l publish/examples
        - ls -l publish/assets/bootstrap/*
      after_script:
        - ./scripts/check-all.sh || travis_terminate 1
        # - ./scripts/deploy/pr.sh || travis_terminate 1
      deploy:
        - provider: script
          script: ./scripts/deploy/firebase.sh --robots-ok dev
          skip_cleanup: true
          on:
            repo: dart-lang/site-webdev
            branch: master
            condition: $CI_TASK == build*
        - provider: script
          script: ./scripts/deploy/firebase.sh --robots-ok dev
          skip_cleanup: true
          on:
            repo: dart-lang/site-webdev
            branch: 5-dev
            condition: $CI_TASK == build*
    - env: CI_TASK="test $TEST_OPT"
      script: gulp $CI_TASK
    - env: CI_TASK="e2e $E2E_OPT1"
      script: gulp $CI_TASK
    - env: CI_TASK="e2e $E2E_OPT2"
      script: gulp $CI_TASK
    - env: CI_TASK="e2e $E2E_OPT3"
      script: gulp $CI_TASK
    - env: CI_TASK="e2e $E2E_OPT1 --web-compiler=dart2js"
      script: gulp $CI_TASK
    - env: CI_TASK="e2e $E2E_OPT2 --web-compiler=dart2js"
      script: gulp $CI_TASK
    - env: CI_TASK="e2e $E2E_OPT3 --web-compiler=dart2js"
      script: gulp $CI_TASK

    # It takes too long to cache built site.
    # ## STAGE ----------------------------------------------
    # - stage: deploy
    #   env: CI_TASK="build"
    #   deploy: ...

# Only run Travis jobs for named branches (to avoid double builds for each PR)
branches:
  only: [master, /^\d(\.x|-dev)$/, /travis-build/]
