dist: trusty
sudo: required
language: node_js
node_js: 6

# cache:
#   bundler: true
#   directories:
#   - $HOME/[path]

env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
    - DISPLAY=:99.0
    - CHROME_BIN=chromium-browser
    - JEKYLL_ENV=production
    - LATEST_RELEASE=3.0.0-alpha+1
  matrix:
    - CI_TASK=build
    - CI_TASK=test
    - CI_TASK="e2e --fast"

matrix:
  fast_finish: true
  allow_failures:
    - env: CI_TASK=test
    - env: CI_TASK="e2e --fast"

before_install:
  - sudo apt-get update --yes
  - source ./scripts/env-set.sh
  - ./scripts/install-dart-sdk.sh
  - ./scripts/before-install.sh
  - rvm install 2.3.0

install:
  - sudo sh -c "echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula
    select true | debconf-set-selections"
  - sudo apt-get install --yes ttf-indic-fonts ttf-mscorefonts-installer ttf-dejavu-core
    ttf-kochi-gothic ttf-kochi-mincho fonts-tlwg-garuda
    # ttf-thai-tlwg # Package 'ttf-thai-tlwg' has no installation candidate
  - ./scripts/install.sh
  - ./scripts/get-ng-repo.sh

before_script:
  - sh -e /etc/init.d/xvfb start
  - t=0; until (xdpyinfo -display :99 &> /dev/null || test $t -gt 10); do sleep 1; let t=$t+1; done
  - content_shell --dump-render-tree

script:
  # - ./scripts/deploy/runtests.sh
  # - ./scripts/deploy/cibuild
  - gulp $CI_TASK

after_script:
  - ./scripts/check-build.sh || travis_terminate 1
  - ./scripts/check-links.sh || travis_terminate 1

# branch whitelist
# branches:
#   only:
#   - master        # test the master branch
#   - /stage-(.*)/  # test every branch which starts with "stage-"

deploy:
  - provider: script
    script: ./scripts/deploy/deploy-firebase-dev.sh
    skip_cleanup: true
    on:
      branch: master
      # Only deploy for GitHub dart-lang/site-webdev, not site forks
      condition: "$TRAVIS_REPO_SLUG == dart-lang/* && $CI_TASK == build"
