dist: trusty
sudo: required
language: node_js
node_js: 6

# cache:
#   bundler: true
#   directories:
#   - $HOME/[path]

env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
    - DISPLAY=:99.0
    - CHROME_BIN=chromium-browser
    - JEKYLL_ENV=production
    # E2E: use --skip=t1|t2|...|tx to skip tests
    - E2E_OPT="--fast"
  matrix:
    - CI_TASK=build DART_CHANNEL=stable
    - CI_TASK=test  DART_CHANNEL=stable
    - CI_TASK=test  DART_CHANNEL=dev
    - CI_TASK="e2e $E2E_OPT" DART_CHANNEL=stable
    - CI_TASK="e2e $E2E_OPT" DART_CHANNEL=stable WEB_COMPILER=dartdevc
    - CI_TASK="e2e $E2E_OPT" DART_CHANNEL=dev WEB_COMPILER=dartdevc
    - CI_TASK="e2e $E2E_OPT" DART_CHANNEL=dev

matrix:
  fast_finish: true
  allow_failures:
    - env: CI_TASK=test  DART_CHANNEL=dev
    - env: CI_TASK="e2e $E2E_OPT" DART_CHANNEL=stable
    - env: CI_TASK="e2e $E2E_OPT" DART_CHANNEL=stable WEB_COMPILER=dartdevc
    - env: CI_TASK="e2e $E2E_OPT" DART_CHANNEL=dev WEB_COMPILER=dartdevc
    - env: CI_TASK="e2e $E2E_OPT" DART_CHANNEL=dev

before_install:
  - source ./scripts/get-ruby.sh
  - source ./scripts/env-set.sh
  - ./scripts/before-install.sh

install:
  - ./scripts/install.sh

before_script:
  - ./scripts/browser.sh

script:
  # - ./scripts/deploy/runtests.sh; ./scripts/deploy/cibuild
  - gulp $CI_TASK

after_script:
  - ./scripts/check-all.sh || travis_terminate 1

# branch whitelist
# branches:
#   only:
#   - master        # test the master branch
#   - /stage-(.*)/  # test every branch which starts with "stage-"

deploy:
  - provider: script
    script: ./scripts/deploy/firebase.sh
    skip_cleanup: true
    on:
      repo: dart-lang/site-webdev
      branch: master
      condition: $CI_TASK == build*
