dist: trusty
sudo: required
language: node_js
node_js: 6

# cache:
#   bundler: true
#   directories:
#   - $HOME/[path]

env:
  global:
    - DART_CHANNEL=stable
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
    - DISPLAY=:99.0
    - CHROME_BIN=chromium-browser
    - JEKYLL_ENV=production
    # E2E and TEST: use --skip=t1|t2|...|tx to skip tests
    # https://github.com/dart-lang/angular/issues/612
    - E2E_OPT1="--fast --filter=examples/ng/doc/[a-s] --skip=dependency-injection"
    - E2E_OPT2="--fast --filter=examples/ng/doc/[t-z]"
    - TEST_OPT=""
    - TZ=US/Pacific # normalize build timestamp
  matrix:
    - CI_TASK="build --dartdoc"
    - CI_TASK="ng-pkg-pub-upgrade" # fails when new ng pkg vers is available
    - CI_TASK="test $TEST_OPT"
    - CI_TASK="e2e $E2E_OPT1"
    - CI_TASK="e2e $E2E_OPT2"
    #- CI_TASK="e2e $E2E_OPT1" WEB_COMPILER=dartdevc
    #- CI_TASK="e2e $E2E_OPT2" WEB_COMPILER=dartdevc

matrix:
  fast_finish: true
  allow_failures:
    - env: CI_TASK="test $TEST_OPT"
    - env: CI_TASK="e2e $E2E_OPT1"
    - env: CI_TASK="e2e $E2E_OPT2"
    - env: CI_TASK="e2e $E2E_OPT1" WEB_COMPILER=dartdevc
    - env: CI_TASK="e2e $E2E_OPT2" WEB_COMPILER=dartdevc

before_install:
  - source ./scripts/get-ruby.sh
  - source ./scripts/env-set.sh
  - ./scripts/before-install.sh

install:
  - ./scripts/install.sh
  - ./scripts/write-ci-info.sh -v

before_script:
  - ./scripts/browser.sh

script:
  # - ./scripts/deploy/runtests.sh; ./scripts/deploy/cibuild
  - gulp $CI_TASK

after_script:
  - ./scripts/check-all.sh || travis_terminate 1

# branch whitelist
# branches:
#   only:
#   - master        # test the master branch
#   - /stage-(.*)/  # test every branch which starts with "stage-"

deploy:
  - provider: script
    script: ./scripts/deploy/firebase.sh
    skip_cleanup: true
    on:
      repo: dart-lang/site-webdev
      branch: master
      condition: $CI_TASK == build*
  - provider: script
    script: ./scripts/deploy/firebase.sh dev
    skip_cleanup: true
    on:
      repo: dart-lang/site-webdev
      branch: 5-dev
      condition: $CI_TASK == build*
