dist: trusty
sudo: required # required because we need to install fonts for content-shell
language: dart
dart: stable
with_content_shell: true

cache:
  timeout: 300
  bundler: true
  directories:
  - $HOME/.pub-cache
  - $HOME/.nvm
  - $HOME/.rvm
  - node_modules
  # - publish # takes too long to cache and check for freshness
  - tmp # TODO: rename to cache or .cache
  # Examples:
  - examples/ng/doc/node_modules

addons:
  chrome: stable

env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
    - DISPLAY=:99.0
    - CHROME_BIN=chromium-browser
    - JEKYLL_ENV=production
    # E2E and TEST: use --skip=t1|t2|...|tx to skip tests
    # https://github.com/dart-lang/angular/issues/612
    - E2E_OPT1="--fast --filter=examples/ng/doc/[a-l] --skip=/dependency-injection"
    - E2E_OPT2="--fast --filter=examples/ng/doc/[m-z] --skip=toh"
    - E2E_OPT3="--fast --filter=examples/ng/doc/toh"
    - TEST_OPT=""
    - TZ=US/Pacific # normalize build timestamp
  matrix:
    - CI_TASK="build --dartdoc --use-cached-api-doc"
    - CI_TASK="ng-pkg-pub-upgrade" # fails when new ng pkg vers is available
    - CI_TASK="test $TEST_OPT"
    - CI_TASK="e2e $E2E_OPT1"
    - CI_TASK="e2e $E2E_OPT2"
    - CI_TASK="e2e $E2E_OPT3"
    #- CI_TASK="e2e $E2E_OPTx --web-compiler=dartdevc"

matrix:
  fast_finish: true
  allow_failures:
    - env: CI_TASK="test $TEST_OPT"
    - env: CI_TASK="e2e $E2E_OPT1"
    - env: CI_TASK="e2e $E2E_OPT2"
    - env: CI_TASK="e2e $E2E_OPT3"

before_install:
  - source ./scripts/env-set.sh
  - ./scripts/before-install.sh

install:
  - ./scripts/install.sh
  - ./scripts/write-ci-info.sh -v

before_script:
  - ./scripts/browser.sh

script:
  # - ./scripts/deploy/runtests.sh; ./scripts/deploy/cibuild
  - gulp $CI_TASK

after_script:
  - ./scripts/check-all.sh || travis_terminate 1
  - ./scripts/deploy/pr.sh || travis_terminate 1

# Only run Travis jobs for named branches (to avoid double builds for each PR)
branches:
  only: [4.x, /travis-build/]

deploy:
  - provider: script
    script: ./scripts/deploy/firebase.sh --robots-ok
    skip_cleanup: true
    on:
      repo: dart-lang/site-webdev
      branch: 4.x
      condition: $CI_TASK == build*
