# Site settings
title: webdev.dartlang.org
description: "Documentation to help you build high-quality web apps, using Dart tools and libraries. Includes AngularDart docs."
url: https://webdev.dartlang.org
dev-url: https://webdev-dartlang-org-dev.firebaseapp.com
permalink: /:categories/:title
repo: https://github.com/dart-lang/site-webdev

# Global variables
# use case:
#   {{site.dartlang}}/downloads
#
dart4web: ""
dartlang: "https://www.dartlang.org"
dart_vm:  "https://www.dartlang.org/dart-vm"
# Use the following when testing both websites locally
# dartlang: "http://localhost:4000"
# dart_vm:  "http://localhost:4000/dart-vm"
flutter:  "https://flutter.io"
dartino:  "https://dartino.org"
dart_api: "https://api.dartlang.org/stable"
acx_api: "/api/angular_components"
flutter_api: "http://docs.flutter.io"
dartino_api: "https://dartino.github.io/api"
api: "https://www.dartdocs.org/documentation"

collections:
  articles:
    output: true
  tutorials:
    output: true
  guides:
    output: true
  codelabs:
    output: true

defaults:
- scope:
    path: ""
    # type: pages
  values:
    layout: default
    toc: true
- scope:
    path: ""
    type: tutorials
  values:
    layout: tutorial
- scope:
    path: ""
    type: codelabs
  values:
    og_type: article
- scope:
    path: _codelabs/angular_components
    type: codelabs
  values:
    # The `image` query parameter is a version number. Change the number after the file has been updated,
    # otherwise the old cached version will be used by Facebook, etc.
    image: /codelabs/angular_components/images/cartoon.jpeg?3
- scope:
    path: _codelabs/ng2
    type: codelabs
  values:
    image: /codelabs/ng2/images/piratemap.jpg?3
- scope:
    path: angular/guide/testing
  values:
    # layout: angular
    status: '(DRAFT)'

custom:
  dartpad:
    embed-dart-prefix: "https://dartpad.dartlang.org/embed-dart.html"
    embed-html-prefix: "https://dartpad.dartlang.org/embed-html.html"
    embed-inline-prefix: "https://dartpad.dartlang.org/embed-inline.html"
    direct-link: "https://dartpad.dartlang.org"
  downloads:
    dartarchive-be-url-prefix: "https://storage.googleapis.com/dart-archive/channels/be/raw"
    dartarchive-dev-url-prefix: "https://storage.googleapis.com/dart-archive/channels/dev/release"
    dartarchive-stable-url-prefix: "https://storage.googleapis.com/dart-archive/channels/stable/release"
    binaries:
      - os: windows
        name: Windows
        ext: zip
        editor-ext: zip
      - os: macos
        name: Mac
        ext: zip
        editor-ext: zip
      - os: linux
        name: Linux
        ext: zip
        editor-ext: zip

# For defaults see:
# https://jekyllrb.com/docs/configuration/#default-configuration

# Build settings
source: src
destination: publish
bundler_args: --without production

# exclude: ['.asset-cache']

keep_files:
  - examples
  - api
  - angular/api
  - components/api

plugins:
- jekyll-assets
- jekyll-toc

assets:
  # compress:
  #   css: true # default - development: false, production: true
  #   js: true # default - development: false, production: true
  # cache: false # default: .asset-cache
  # cdn: https://cdn.example.com
  # skip_baseurl_with_cdn: false
  # skip_prefix_with_cdn: false
  prefix: "/assets"
  assets:
    - "*.png"
    - "*.jpg"
    - "*.eot"
    - "*.ttf"
    - "*.woff"
    - "*.svg"
  #   - "bundle.css"
  # digest: true
  sources:
    - _assets/icons
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
  features:
    liquid: true # default: false
    automatic_img_size: true # default: true
    automatic_img_alt : true # default: true
