name: ng_test.github_issues
description: Demo of angular_test
version: 0.0.1
environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  angular: ^4.0.0
  angular_forms: ^1.0.0
  markdown: ^0.11.3
  ng_bootstrap: ^0.8.4
  sass_transformer: ^0.1.2+1

dev_dependencies:
  angular_test: ^1.0.0
  browser: ^0.10.0+2
  dart_to_js_script_rewriter: ^1.0.1
  mockito: ^2.0.2
  pageloader: ^2.2.5
  test: ^0.12.30

transformers:
- angular:
    entry_points:
    - web/main.dart
    - test/**_test.dart
- test/pub_serve:
    $include: test/**_test.dart
- dart_to_js_script_rewriter
