name: angular_tour_of_heroes
description: Tour of Heroes
version: 0.0.1

environment:
  sdk: '>=2.3.1 <3.0.0'

dependencies:
  angular: ^5.3.0
  angular_forms: ^2.1.2
  angular_router: ^2.0.0-alpha+22

dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.3.3
  build_test: ^0.10.7
  build_web_compilers: ^2.1.0
  mockito: ^4.0.0
  pageloader: ^3.2.0
  test: ^1.6.3
