name: components_codelab
description: An AngularDart app that simulates a lottery
version: 0.0.1

environment:
  sdk: '>=2.3.1 <3.0.0'

dependencies:
  angular: ^5.3.1
  angular_components: 0.13.0+1
  intl: ^0.15.0

dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.7.0
  build_test: ^0.10.8
  build_web_compilers: ^2.4.0
  test: ^1.6.3
