name: angular_tour_of_heroes
description: Tour of Heroes
version: 0.0.1

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.0.0

# #docregion dev_dependencies, build-dependencies
dev_dependencies:
  # #enddocregion build-dependencies
  angular_test: ^2.0.0
  # #docregion build-dependencies
  build_runner: ^1.0.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  # #enddocregion build-dependencies
  test: ^1.0.0
# #enddocregion dev_dependencies
