# #docregion
name: angular_tour_of_heroes
description: Tour of Heroes
version: 0.0.1

environment:
  sdk: '>=2.0.0-dev.48.0 <2.0.0'

dependencies:
  angular: ^5.0.0-alpha

# #docregion dev_dependencies, build-dependencies
dev_dependencies:
  # #enddocregion build-dependencies
  angular_test: ^2.0.0-alpha
  # #docregion build-dependencies
  build_runner: ^0.8.6
  build_test: ^0.10.2
  build_web_compilers: ^0.3.7
  # #enddocregion build-dependencies
  test: ^0.12.30
# #enddocregion dev_dependencies
