name: angular_tour_of_heroes
description: Tour of Heroes
version: 0.0.1

environment:
  sdk: '>=2.0.0-dev.51.0 <2.0.0'

dependencies:
  angular: ^5.0.0-alpha
  angular_forms: ^2.0.0-alpha

dev_dependencies:
  angular_test: ^2.0.0-alpha
  build_runner: ^0.8.6
  build_test: ^0.10.2
  build_web_compilers: ^0.3.7
  test: ^0.12.30

dependency_overrides:
  # Temporarily use mock pageloader (https://github.com/dart-lang/site-webdev/issues/1351):
  pageloader:
     git:
       url: https://github.com/dart-lang/site-webdev.git
       path: examples/util/pageloader
#    path: ../../../util/pageloader
