name: pageloader
description: >
  Pageloader mock to be used until v3 is released;
  for details, see https://github.com/dart-lang/site-webdev/issues/1351
version: 0.0.1

environment:
  sdk: '>=2.3.1 <3.0.0'

dependencies:
  angular_test: ^2.3.0

dev_dependencies:
  test: ^1.6.3
