name: ngzone
description: A simple AngularDart app
version: 0.0.1

environment:
  sdk: '>=2.3.1 <3.0.0'

dependencies:
  angular: ^5.3.0

dev_dependencies:
  build_runner: ^1.3.1
  build_test: ^0.10.8
  build_web_compilers: ^2.4.0
