name: angular_tour_of_heroes
description: Tour of Heroes
version: 0.0.1

environment:
  sdk: '>=2.3.1 <3.0.0'

dependencies:
  angular: ^6.0.0-alpha
  angular_forms: ^2.1.0

dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.3.0
  build_test: ^0.10.0
  build_web_compilers: ^2.4.0
  pageloader: ^3.2.0
  test: ^1.6.3
