# #docplaster
name: router_example
description: Router Example
version: 0.0.1

environment:
  sdk: '>=2.0.0-dev.46.0 <2.0.0'

# #docregion dependencies, dependencies-wo-forms
dependencies:
  angular: ^5.0.0-alpha
  # #enddocregion dependencies-wo-forms
  angular_forms: ^2.0.0-alpha
  # #docregion dependencies-wo-forms
  angular_router: ^2.0.0-alpha
# #enddocregion dependencies, dependencies-wo-forms

dev_dependencies:
  build_runner: ^0.8.2
  build_test: ^0.10.0
  build_web_compilers: ^0.3.6
