name: fetch_data_example
description: Fetch data example
version: 0.0.1

environment:
  sdk: '>=2.3.1 <3.0.0'

dev_dependencies:
  build_runner: ^1.7.0
  build_web_compilers: ^2.4.0
  test: ^1.6.3
#  dartlang_examples_util:
#    git:
#      url: https://github.com/dart-lang/site-www.git
#      path: examples/util
