# #docregion , additions
name: angular_tour_of_heroes
# #enddocregion additions
description: Tour of Heroes
version: 0.0.1
environment:
  sdk: '>=1.24.0 <2.0.0'
  # #docregion additions
dependencies:
  angular2: ^3.1.0
  http: ^0.11.0
  stream_transform: ^0.0.6
  # #enddocregion additions
dev_dependencies:
  angular_test: ^1.0.0-beta+2
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  mockito: ^2.0.2
  test: ^0.12.21
  # #docregion additions
transformers:
- angular2:
    entry_points: web/main.dart
    resolved_identifiers:
        BrowserClient: 'package:http/browser_client.dart'
        Client: 'package:http/http.dart'
# #enddocregion additions
- angular2/transform/reflection_remover:
    $include: test/**_test.dart
- test/pub_serve:
    $include: test/**_test.dart
- dart_to_js_script_rewriter
web:
  compiler:
    debug: dartdevc
