name: angular_tour_of_heroes
description: Tour of Heroes
version: 0.0.1

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  angular: ^5.3.1
  angular_forms: ^2.1.0
  angular_router: ^2.0.0-alpha
  http: ^0.12.0
  stream_transform: ^1.0.0

dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.3.0
  build_test: ^0.10.0
  build_web_compilers: ^2.4.0
  mockito: ^4.0.0
  pageloader: ^3.2.0
  test: ^1.6.0
