# #docregion
name: angular_app
description: A web app that uses AngularDart
version: 0.0.1

environment:
  sdk: '>=2.0.0-dev.46.0 <2.0.0'

dependencies:
  angular: ^5.0.0-alpha

# #docregion dev_dependencies, build-dependencies
dev_dependencies:
  # #enddocregion build-dependencies
  angular_test: ^2.0.0-alpha
  # #docregion build-dependencies
  build_runner: ^0.8.2
  build_test: ^0.10.0
  build_web_compilers: ^0.3.6
  # #enddocregion build-dependencies
  test: ^0.12.30
# #enddocregion dev_dependencies
